### ISSUE TITLE
Unable to retrieve document from URI (Windows)

### ISSUE THREAD

**Issue by swiffer** [grafana/grafana-vs-code-extension#55]
When clicking "Edit in Grafana" I'm getting the error as shown in the screenshot below (Windows).

![grafik](https://github.com/grafana/grafana-vs-code-extension/assets/2990373/98a90add-c46f-40e1-bce4-150fc925ad39)

**Comment by malcolmholmes** [comment]
How large is the file? [This](https://github.com/microsoft/vscode/issues/31078) suggests there's a 5Mb limit :-(

**Comment by swiffer** [comment]
No, it's really tiny, ~ 15kb

**Comment by malcolmholmes** [comment]
Hmmm. Unfortunately, that error doesn't help me a great deal. Is there any more to it? It seems to be an error from vscode, not from the extension itself. Is the file in one line, perchance?

**Comment by swiffer** [comment]
after i click "Edit in Grafana" the whole content of the folder is missing. in addition the breadcrumb navigation of the editor looks strange...

![grafik](https://github.com/grafana/grafana-vs-code-extension/assets/2990373/32d8b679-5565-4a79-b756-c9b393065f3c)

**Comment by malcolmholmes** [comment]
can you try something? Rename your file to `*.grafana` instead of `*.json`. Then you don't need to right click, just select the file and it should open. Does that work for you?

Still need to fix the `.json` version, but would be good to know if this works for you (it does for me).

**Comment by malcolmholmes** [comment]
@swiffer I *think* #57 fixes this. Can you try it? If it works, I can roll out a new release to the marketplace.

**Comment by malcolmholmes** [comment]
Yes, "run from repository", or I can share a vsix file

**Comment by malcolmholmes** [comment]
We've seen a few confirmations of #57, so I've merged and released it. Can you update your extension from the marketplace (v0.0.11) and let me know if this fixes it?

**Comment by swiffer** [comment]
👍 it's working now. thanks - real timesaver!
