### ISSUE TITLE
Additional ways to invoke the extension

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/grafana-vs-code-extension#68]
Currently, right clicking on a file in the file explorer offers an 'Edit in Grafana' option.

There are additional opportunities to invoke the extension, including:
* Right clicking on the filename in the editor tab, brings up a context menu. "Edit in Grafana" could be included there.
* When editing a Markdown file, an icon appears that gives the option for side-by-side preview. A similarly placed icon could allow for opening the extension. Note, this icon may also be available in the jsonnet vscode extension (so a good place to look for how to make it work).

**Comment by eric-engberg** [comment]
The ability to open a "new" dashboard would be nice.  Currently have to copy/paste a dashboard to create a "new" one.

**Comment by spinillos** [comment]
The side-by-side feature issue is defined here: https://github.com/grafana/grafana-vs-code-extension/issues/69

So we are closing this one since the rest of features are already done.
