### ISSUE TITLE
More Grafana usecases

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/grafana-vs-code-extension#71]
Currently, the context menu offers "Edit in Grafana" as the only choice. More options could be added, for example:
* **Grafana: Edit Dashboard**: current behaviour
* **Grafana: Explore query**: when cursor is on a query in a json file, grab the query from the JSON, parse the JSON, identify the datasource, and render an Grafana Explore URL with the correct datasource and query.

**Comment by spinillos** [comment]
We aren't going to do anything for now.
