### ISSUE TITLE
Unable to use library panels

### ISSUE THREAD

**Issue by DigiNecro** [grafana/grafana-vs-code-extension#79]
Hi,

I would like to use libray panels, but it seems not work. I created one in Grafana directly, but if I want do add a Library Panel in my dashboard with this plugin I get a error and the frame to select a panel is empty.

```
Error
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot GET /api/library-elements</pre> </body> </html>
```

I tried to export a dashboard with a library panel an open it in VSC but it couldn't load the panel either.

The support of creeating and using library panels would help us very much.

Thanks for your plugin and help!

Environment
VSC: 1.85.2
Grafana Plugin: v0.0.15
Grafana: Latest Enterprise (without license) as docker container in a docker swarm

**Comment by DigiNecro** [comment]
With Postman "/api/library-elements" I get a correct response

**Comment by K-Phoen** [comment]
Thanks for opening this issue. The next release will support library panels :)

**Comment by DigiNecro** [comment]
Thank you very much!

I'm happy about hearing these good news! :)
