### ISSUE TITLE
Unable to open dashboard with Grafana Cloud instance configured

### ISSUE THREAD

**Issue by gthompson280** [grafana/grafana-vs-code-extension#86]
Hi all,

Am using VSCode extension v0.0.17 and when trying to open a dashboard with a Grafana Cloud instance configured (using Admin role service account token), am just getting the Grafana icon bouncing indefinitely. Most recently tested with Grafana Cloud v11.3.0-75420.

To contrast, I have no issues opening the same dashboard in Grafana when using an on-prem Grafana instance on v11.1.4.

If more information is needed, please let me know. Thanks!

**Comment by K-Phoen** [comment]
Thanks for reporting this issue. A fix was merged recently and it will be included in the next release (to be shipped *soon* ™)
